### ISSUE TITLE
Random question

### ISSUE THREAD

**Issue by jpb2288** [opeyemibami/wine-quality-prediction-web-app#9]
Hi 

I just was wondering why you reduced to three bins the quality levels? That variable changed from [3:9] to [0:2]

Thanks

**Comment by opeyemibami** [comment]
These classes were reduced to 3 bins with the aim of labelling the wines with qualities “Low”, “Ave” and “High”
Check the article out for a better understanding (https://heartbeat.comet.ml/deploy-a-machine-learning-model-as-a-web-application-part-1-a1c1ff624f7a

**Comment by jpb2288** [comment]
Thank you so much. Maybe my question was not clear enough. I mean, after the reclassify process was done, almost all wines are labeled as “Average”. The question is ¿there is any strong reason to select those ranges, even when it meant loss of variability in the output?

**Comment by opeyemibami** [comment]
The variability in the output is not balanced, reducing this output into small categories helps in shifting the focus of the dataset and reduces the chances of misclassification.
